### PR TITLE
Embed JSON assets within the library

### PR DESCRIPTION
**Pull request by fayzanx**
- Embeds the assets directory using `include_dir` crate.
- Retains internationalization, user can provide own files.
- Update file names, variables for consistency

File loading can be made into a separate helper function to avoid duplication, should we create an issue for that @rm-Umar ?

### CODE REVIEW

**Comment by rm-Umar** [comment]
> File loading can be made into a separate helper function to avoid duplication, should we create an issue for that @rm-Umar ?
Yes, we can do that in the future if we need to load another file.

**Review by rm-Umar — APPROVED** [review]
Can you change the `JSON` file names back to original for the consistency as we are using same names in all other SDKs.

**Comment by rm-Umar** [comment]
Seems good to me, @UmanShahzad can you do a final check before merging it?

**Review by UmanShahzad — APPROVED** [review]
Go for it and we can maybe make a fake test app that uses this library, in some subdirectory. I did this in the nodejs SDK for similar reasons.

Can do that in a separate PR though, just make an issue for it @rm-Umar @fayzanx

**Review by rm-Umar — APPROVED** [review]

**Pull request merged**
