### PR TITLE
Upgraded reqwest to 0.12

### PR DESCRIPTION
**Pull request by rakshith-ravi**
Ran `cargo test` with my token and all tests seem to pass

### CODE REVIEW

**Review by Alextopher — APPROVED** [review]

**Comment by Alextopher** [comment]
Hi @UmanShahzad this PR is getting a little stale.

Thank you for everything you do and great products.

**Comment by rakshith-ravi** [comment]
For anybody looking to use this with your project, add this to your `Cargo.toml`:

```toml
ipinfo = { git = "https://github.com/rakshith-ravi/ipinfo-rust", branch = "feature/upgrade-reqwest" }
```

**Comment by abdullahdevrel** [comment]
Hey guys, we went through a transition in the engineering team and have some backlog of unresolved issues. We will try our best to address any open issues and PRs as soon as possible.

---
@max-ipinfo Can you review the issue, please?

**Comment by rakshith-ravi** [comment]
Rebased and reopened #59

**Pull request closed without merging**
